apiVersion: v1
kind: Service
metadata:
  labels:
    app: iib-lrq
  name: iib-lrq
  namespace: 3htp
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 7800
    protocol: TCP
    targetPort: 7800
  - name: console
    port: 4414
    protocol: TCP
    targetPort: 4414
  selector:
    app: iib-lrq
  sessionAffinity: None
  type: NodePort
